config/routes.rb
Hb::Application.routes.draw do
  resources :advice_requests

  resources :user_tracks

  get "flatuipro_demo/index"
  root to: 'homes#show', via: :get

  devise_for :users,
    controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_scope :user do
    get "users/sign_out", to: 'devise/sessions#destroy', as: :sign_out
  end

  resources :campaigns, only: [:index, :show, :new, :create, :destroy] do
    resources :reservations, only: [:create]
  end
  get 'music', to: 'campaigns#index', as: :music

  resource :launchbase, only: [:show]
  resource :artist_lounge, only: [:show]
  resource :user_settings, only: [:show]
  resources :musicians, only: [:show]
  resources :uploads


  get 'soundcloud/connect', to: 'soundcloud_connection#connect',
    as: :soundcloud_connect
  get 'soundcloud/connected', to: 'soundcloud_connection#connected',
    as: :soundcloud_connected
  delete 'soundcloud/disconnect', to: 'soundcloud_connection#disconnect',
    as: :disconnect_soundcloud

  get 'dashboard', to: 'dashboards#home'

  get 'pages/home' => 'high_voltage/pages#about', id: 'about'
  get 'pages/home' => 'high_voltage/pages#privacy', id: 'privacy'
  get 'pages/home' => 'high_voltage/pages#fans', id: 'fans'
  get 'pages/home' => 'high_voltage/pages#musicians', id: 'musicians'

  get '/delayed_job', to: DelayedJobWeb, anchor: false
end

app/models/artist_lounge.rb
class ArtistLounge
  def initialize(artist)
    @artist = artist
  end

  def campaigns
    @artist.campaigns
  end

  def campaign_count
    campaigns.count
  end

  def soundcloud_avatar
    @artist.soundcloud_avatar
  end

  def soundcloud_followers
    @artist.soundcloud_followers_count
  end

  def musician_description
    @artist.description
  end

  def download_counts
    @artist.total_campaign_download_count
  end

  def playcount
    @artist.total_campaign_playcount
  end
end

app/controllers/artist_lounges_controller.rb
class ArtistLoungesController < AuthorizedController
  def show
    @lounge = ArtistLounge.new(musician)
  end

  private

  def musician
    current_user.musician
  end
end

app/views/artist_lounges/_menu.html.erb
 <div class="span2 backcolumn">
          <div class=" sidebar-nav dashboardmenu">
            <ul class="nav nav-list">
              <li class="active"><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "campaignsicon.png", class: "dashboardicons" %> Campaigns</p>
                <% end %>
              </li>
              <li><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "songviceicon.png", class: "dashboardicons" %> SongVice</p>
                <% end %>
              </li>
              <li ><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "schedulericon.png", class: "dashboardicons" %> Scheduler</p>
                <% end %>
              </li>
              <li ><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "newslettersicon.png", class: "dashboardicons" %> Newsletters</p>
                <% end %>
              </li>
              <li ><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "promoicon.png", class: "dashboardicons" %> Promos</p>
                <% end %>
              </li>
              <li ><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "analyticsicon.png", class: "dashboardicons" %> Analytics</p>
                <% end %>
              </li>
              <li ><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "masteringicon.png", class: "dashboardicons" %> Mastering</p>
                <% end %>
              </li>
              <li><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "mailinglistsicon.png", class: "dashboardicons" %> Mailing Lists</p>
                <% end %>
              </li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->

app/views/artist_lounges/show.html.erb
<% content_for(:extra_body_classes, 'background-light sidebar-hidden') %>
 <div class="wrap" id="home">
    <div class="content container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <h2 class="page-title pull-left">Dashboard</h2>
          <%= link_to user_settings_path do %>
            <button type="button" class="btn btn-info pull-right"
              data-placement="top"
              data-original-title=".btn .btn-info .btn-large .pull-right">
              &nbsp;<i class="icon-cog"></i> Account Settings&nbsp;
            </button>
          <% end %>
        </div>
      </div>
      <div class="row-fluid box-row">
        <div class="span2">
          <div class="box">
            <div class="icon">
              <i class="icon-calendar"></i>
            </div>
            <div class="description">
              <strong><%= @lounge.campaign_count %></strong> active campaigns
            </div>
          </div>
        </div>
        <div class="span2">
          <div class="box">
            <div class="big-text">
              <%= @lounge.playcount %>
            </div>
            <div class="description">
              <i class="icon-play"></i>
              Total Plays
            </div>
          </div>
        </div>
        <div class="span2">
          <div class="box">
            <div class="big-text">
              <%= @lounge.soundcloud_followers %>
            </div>
            <div class="description">
              <i class="icon-group"></i>
              Soundcloud followers
            </div>
          </div>
        </div>
        <div class="span2">
          <div class="box">
            <div class="big-text">
              <%= @lounge.download_counts %>
            </div>
            <div class="description">
              <i class="icon-download"></i>
              downloads
            </div>
          </div>
        </div>
        <div class="span2">
          <div class="box">
            <div class="big-text">
              pro
            </div>
            <div class="description">
              coming soon
            </div>
          </div>
        </div>
        <div class="span2">
          <div class="box">
            <div class="big-text">
              pro
            </div>
            <div class="description">
              coming soon
            </div>
          </div>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span9 widget hidden-phone">
          <h4 class="pull-left">Campaign Manager</h4>
        </div>
        <div class="span3 widget hidden-phone">
          <%= link_to new_campaign_path do %>
            <button type="submit"
              class="btn btn-info btn-large btncampaign">
              <i class="icon-plus"></i> New Campaign
            </button>
          <% end %>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span9 widget">
          <div class="body">
          <table id="datatable-table" class="table table-hover">
            <thead>
              <tr>
                <th>Id</th>
                <th>Name</th>
                <th class="no-sort">Artwork</th>
                <th class="hidden-phone-landscape">Requested</th>
                <th class="hidden-phone-landscape">Achieved</th>
                <th>Progress</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
            <% @lounge.campaigns.each do |campaign| -%>
              <tr>
                <td><%= campaign.id %></td>
                <td><%= campaign.name %></td>
                <td>
                  <%= link_to campaign.track_permalink, class: 'stratus' do %>
                    <%= image_tag campaign.artwork_for_track,
                      { style: "height: 25px;" } %>
                    <% end %>
                </td>
                <td><%= campaign.requested_likes %></td>
                <td><%= campaign.reserved %></td>
                <td><%= campaign.progress %>%</td>
                <td>
                  <%= button_to 'Delete',
                    campaign_path(campaign),
                    method: :delete,
                    data: { confirm: "This campaign will be deleted, are you sure?" },
                    class: 'btn btn-small btn-danger'
                  %>
                </td>
              </tr>
            <% end -%>
            </tbody>
          </table>
        </div>
      </div>
        <div class="span3">
          <div class="widget">
            <h4>Musician Profile</h4>
            <h5>
              <%= image_tag @lounge.soundcloud_avatar,
                { style: "height: 25px;" } %>
            </h5>
            <p class="hidden-iphone">
              <%= truncate(@lounge.musician_description, length: 400) %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/artist_lounges/showold.html.erb
<% content_for(:extra_body_classes, 'background-light sidebar-hidden') %>
 <div class="wrap" id="home">
    <div class="content container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <h2 class="page-title pull-left">Dashboard</h2>
          <%= link_to user_settings_path do %>
            <button type="button" class="btn btn-info pull-right"
              data-placement="top"
              data-original-title=".btn .btn-info .btn-large .pull-right">
              &nbsp;<i class="icon-cog"></i> Account Settings&nbsp;
            </button>
          <% end %>
        </div>
      </div>
      <div class="row-fluid box-row">
        <div class="span2">
          <div class="box">
            <div class="icon">
              <i class="icon-calendar"></i>
            </div>
            <div class="description">
              <strong><%= @lounge.campaign_count %></strong> active campaigns
            </div>
          </div>
        </div>
        <div class="span2">
          <div class="box">
            <div class="big-text">
              <%= @lounge.campaigns.sum { |c| c.playcount } %>
            </div>
            <div class="description">
              <i class="icon-play"></i>
              Total Plays
            </div>
          </div>
        </div>
        <div class="span2">
          <div class="box">
            <div class="big-text">
              <%= @lounge.soundcloud_followers %>
            </div>
            <div class="description">
              <i class="icon-group"></i>
              Soundcloud followers
            </div>
          </div>
        </div>
        <div class="span2">
          <div class="box">
            <div class="big-text">
              <%= @lounge.download_counts %>
            </div>
            <div class="description">
              <i class="icon-download"></i>
              downloads
            </div>
          </div>
        </div>
        <div class="span2">
          <div class="box">
            <div class="big-text">
              pro
            </div>
            <div class="description">
              coming soon
            </div>
          </div>
        </div>
        <div class="span2">
          <div class="box">
            <div class="big-text">
              pro
            </div>
            <div class="description">
              coming soon
            </div>
          </div>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span9 widget hidden-phone">
          <h4 class="pull-left">Campaign Manager</h4>
        </div>
        <div class="span3 widget hidden-phone">
          <%= link_to new_campaign_path do %>
            <button type="submit"
              class="btn btn-info btn-large btncampaign">
              <i class="icon-plus"></i> New Campaign
            </button>
          <% end %>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span9 widget">
          <div class="body">
          <table id="datatable-table" class="table table-hover">
            <thead>
              <tr>
                <th>Id</th>
                <th>Name</th>
                <th class="no-sort">Artwork</th>
                <th class="hidden-phone-landscape">Requested</th>
                <th class="hidden-phone-landscape">Achieved</th>
                <th>Progress</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
            <% @lounge.campaigns.each do |campaign| -%>
              <tr>
                <td><%= campaign.id %></td>
                <td><%= campaign.name %></td>
                <td>
                  <%= link_to campaign.track_permalink, class: 'stratus' do %>
                    <%= image_tag campaign.artwork_for_track,
                      { style: "height: 25px;" } %>
                    <% end %>
                </td>
                <td><%= campaign.requested_likes %></td>
                <td><%= campaign.reserved %></td>
                <td><%= campaign.progress %>%</td>
                <td>
                  <%= button_to 'Delete',
                    campaign_path(campaign),
                    method: :delete,
                    confirm: "This campaign will be deleted, are you sure?",
                    class: 'btn btn-small btn-danger'
                  %>
                </td>
              </tr>
            <% end -%>
            </tbody>
          </table>
        </div>
      </div>
        <div class="span3">
          <div class="widget">
            <h4>Musician Profile</h4>
            <h5>
              <%= image_tag @lounge.soundcloud_avatar,
                { style: "height: 25px;" } %>
            </h5>
            <p class="hidden-iphone">
              <%= truncate(@lounge.musician_description, length: 400) %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>