config/routes.rb
Hb::Application.routes.draw do
  resources :advice_requests

  resources :user_tracks

  get "flatuipro_demo/index"
  root to: 'homes#show', via: :get

  devise_for :users,
    controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_scope :user do
    get "users/sign_out", to: 'devise/sessions#destroy', as: :sign_out
  end

  resources :campaigns, only: [:index, :show, :new, :create, :destroy] do
    resources :reservations, only: [:create]
  end
  get 'music', to: 'campaigns#index', as: :music

  resource :launchbase, only: [:show]
  resource :artist_lounge, only: [:show]
  resource :user_settings, only: [:show]
  resources :musicians, only: [:show]
  resources :uploads


  get 'soundcloud/connect', to: 'soundcloud_connection#connect',
    as: :soundcloud_connect
  get 'soundcloud/connected', to: 'soundcloud_connection#connected',
    as: :soundcloud_connected
  delete 'soundcloud/disconnect', to: 'soundcloud_connection#disconnect',
    as: :disconnect_soundcloud

  get 'dashboard', to: 'dashboards#home'

  get 'pages/home' => 'high_voltage/pages#about', id: 'about'
  get 'pages/home' => 'high_voltage/pages#privacy', id: 'privacy'
  get 'pages/home' => 'high_voltage/pages#fans', id: 'fans'
  get 'pages/home' => 'high_voltage/pages#musicians', id: 'musicians'

  get '/delayed_job', to: DelayedJobWeb, anchor: false
end

app/controllers/dashboards_controller.rb
class DashboardsController < AuthorizedController

	def home
	end

end

app/views/dashboards/_menu.html.erb
 <div class="span2 backcolumn">
          <div class=" sidebar-nav dashboardmenu">
            <ul class="nav nav-list">
              <li><%= link_to dashboard_path do %>
                <p class="dashboardtext"><%= image_tag "compass.png", class: "dashboardicons" %> Dashboard</p>
                <% end %>
              </li>
              <li><%= link_to advice_requests_path do %>
                <p class="dashboardtext"><%= image_tag "songviceicon.png", class: "dashboardicons" %> SongVice</p>
                <% end %>
              </li>
              <li><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "campaignsicon.png", class: "dashboardicons" %> Campaigns</p>
                <% end %>
              </li>
              <li ><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "schedulericon.png", class: "dashboardicons" %> Scheduler</p>
                <% end %>
              </li>
              <li ><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "newslettersicon.png", class: "dashboardicons" %> Newsletters</p>
                <% end %>
              </li>
              <li ><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "promoicon.png", class: "dashboardicons" %> Promos</p>
                <% end %>
              </li>
              <li ><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "analyticsicon.png", class: "dashboardicons" %> Analytics</p>
                <% end %>
              </li>
              <li><%= link_to artist_lounge_path do %>
                <p class="dashboardtext"><%= image_tag "mailinglistsicon.png", class: "dashboardicons" %> Mailing Lists</p>
                <% end %>
              </li>
            </ul>
          </div><!--/.well -->
  </div><!--/span-->

app/views/dashboards/home.html.erb
<div class="container-fluid dashboard">
      <div class="row-fluid">
        <%= render 'menu' %>
        <div class="span10">
          <div class="dashboardheader">
            <h4 class="pull-left">Welcome to Your Command Center</h4>
          </div>
          <div class="row-fluid dashboardmain">
            
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->

      <hr>


    </div>