config/routes.rb
Hb::Application.routes.draw do
  resources :advice_requests

  resources :user_tracks

  get "flatuipro_demo/index"
  root to: 'homes#show', via: :get

  devise_for :users,
    controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_scope :user do
    get "users/sign_out", to: 'devise/sessions#destroy', as: :sign_out
  end

  resources :campaigns, only: [:index, :show, :new, :create, :destroy] do
    resources :reservations, only: [:create]
  end
  get 'music', to: 'campaigns#index', as: :music

  resource :launchbase, only: [:show]
  resource :artist_lounge, only: [:show]
  resource :user_settings, only: [:show]
  resources :musicians, only: [:show]
  resources :uploads


  get 'soundcloud/connect', to: 'soundcloud_connection#connect',
    as: :soundcloud_connect
  get 'soundcloud/connected', to: 'soundcloud_connection#connected',
    as: :soundcloud_connected
  delete 'soundcloud/disconnect', to: 'soundcloud_connection#disconnect',
    as: :disconnect_soundcloud

  get 'dashboard', to: 'dashboards#home'

  get 'pages/home' => 'high_voltage/pages#about', id: 'about'
  get 'pages/home' => 'high_voltage/pages#privacy', id: 'privacy'
  get 'pages/home' => 'high_voltage/pages#fans', id: 'fans'
  get 'pages/home' => 'high_voltage/pages#musicians', id: 'musicians'

  get '/delayed_job', to: DelayedJobWeb, anchor: false
end

app/models/advice_request.rb
class AdviceRequest < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
end

app/controllers/advice_requests_controller.rb
class AdviceRequestsController < ApplicationController
  before_action :set_advice_request, only: [:show, :edit, :update, :destroy]

  # GET /advice_requests
  def index
    @advice_requests = AdviceRequest.all
    @user_advice_requests = current_user.advice_requests
  end

  # GET /advice_requests/1
  def show
  end

  # GET /advice_requests/new
  def new
    @advice_request = user.advice_requests.new
  end

  # GET /advice_requests/1/edit
  def edit
  end

  # POST /advice_requests
  def create
    @advice_request = user.advice_requests.build(advice_request_params)

    if @advice_request.save
      redirect_to @advice_request, notice: 'Advice request was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /advice_requests/1
  def update
    if @advice_request.update(advice_request_params)
      redirect_to @advice_request, notice: 'Advice request was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /advice_requests/1
  def destroy
    @advice_request.destroy
    redirect_to advice_requests_url, notice: 'Advice request was successfully destroyed.'
  end

  private

   def user
    current_user
  end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_advice_request
      @advice_request = AdviceRequest.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def advice_request_params
      params.require(:advice_request).permit(:comment, :category_id, :user_id, :drums, :bass, :vocals, :synths, :structure, :effects, :mixing, :master, :track_url)
    end
end

app/views/advice_requests/_form.html.erb
<%= simple_form_for(@advice_request) do |f| %>
  <% if @advice_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advice_request.errors.count, "error") %> prohibited this advice_request from being saved:</h2>

      <ul>
      <% @advice_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    </br>
    <%= f.input :track_url, collection: current_user.uploads.collect {|t|  [t.upload_file_name, t.upload] },required: true, label: "choose the track " %>
    <%= f.input :comment, required: true %></br>
    <%= f.association :category, required: true %></br>
    <%= f.input :drums %></br>
    <%= f.input :bass %></br>
    <%= f.input :vocals %></br>
    <%= f.input :synths %></br>
    <%= f.input :structure %></br>
    <%= f.input :effects %></br>
    <%= f.input :mixing %></br>
    <%= f.input :master %></br>
    <%= f.submit %>
<% end %>

app/views/advice_requests/edit.html.erb
<div class="container">
<h1>Editing advice_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @advice_request %> |
<%= link_to 'Back', advice_requests_path %>
</div>

app/views/advice_requests/index.html.erb
<div class="container-fluid dashboard">
      <div class="row-fluid">
        <%= render 'dashboards/menu' %>
        <div class="span10 ">
          <div class="dashboardheader">
            <h4 class="pull-left">SongVice</h4>

            <%= link_to "Request Advice", new_advice_request_path, class: "btn btn-large btn-info pull-right" %>
          </div>
          <div class="row-fluid dashboardmain">
           
           <table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Track URL</th>
      <th>Category</th>
      <th>Created</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_advice_requests.each do |advice_request| %>
      <tr>
        <td><%= advice_request.track_url %></td>
        <td><%= advice_request.category_id %></td>
        <td><%= time_ago_in_words(advice_request.created_at) %> ago </td>
        <td><%= link_to 'Show', advice_request %></td>
        <td><%= link_to 'Edit', edit_advice_request_path(advice_request) %></td>
        <td><%= link_to 'Destroy', advice_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->

      <hr>


    </div>

app/views/advice_requests/new.html.erb
<div class="container">
<h1>New advice_request</h1>

<%= render 'form' %>

<%= link_to 'Back', advice_requests_path %>
</div>

app/views/advice_requests/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Track Url:</strong>
  <%= @advice_request.track_url %>
</p>
<p>
  <strong>Comment:</strong>
  <%= @advice_request.comment %>
</p>

<p>
  <strong>Category:</strong>
  <%= @advice_request.category_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @advice_request.user_id %>
</p>

<p>
  <strong>Drums:</strong>
  <%= @advice_request.drums %>
</p>

<p>
  <strong>Bass:</strong>
  <%= @advice_request.bass %>
</p>

<p>
  <strong>Vocals:</strong>
  <%= @advice_request.vocals %>
</p>

<p>
  <strong>Synths:</strong>
  <%= @advice_request.synths %>
</p>

<p>
  <strong>Structure:</strong>
  <%= @advice_request.structure %>
</p>

<p>
  <strong>Effects:</strong>
  <%= @advice_request.effects %>
</p>

<p>
  <strong>Mixing:</strong>
  <%= @advice_request.mixing %>
</p>

<p>
  <strong>Master:</strong>
  <%= @advice_request.master %>
</p>

<%= link_to 'Edit', edit_advice_request_path(@advice_request) %> |
<%= link_to 'Back', advice_requests_path %>
</div>