config/routes.rb
Hb::Application.routes.draw do
  resources :advice_requests

  resources :user_tracks

  get "flatuipro_demo/index"
  root to: 'homes#show', via: :get

  devise_for :users,
    controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_scope :user do
    get "users/sign_out", to: 'devise/sessions#destroy', as: :sign_out
  end

  resources :campaigns, only: [:index, :show, :new, :create, :destroy] do
    resources :reservations, only: [:create]
  end
  get 'music', to: 'campaigns#index', as: :music

  resource :launchbase, only: [:show]
  resource :artist_lounge, only: [:show]
  resource :user_settings, only: [:show]
  resources :musicians, only: [:show]
  resources :uploads


  get 'soundcloud/connect', to: 'soundcloud_connection#connect',
    as: :soundcloud_connect
  get 'soundcloud/connected', to: 'soundcloud_connection#connected',
    as: :soundcloud_connected
  delete 'soundcloud/disconnect', to: 'soundcloud_connection#disconnect',
    as: :disconnect_soundcloud

  get 'dashboard', to: 'dashboards#home'

  get 'pages/home' => 'high_voltage/pages#about', id: 'about'
  get 'pages/home' => 'high_voltage/pages#privacy', id: 'privacy'
  get 'pages/home' => 'high_voltage/pages#fans', id: 'fans'
  get 'pages/home' => 'high_voltage/pages#musicians', id: 'musicians'

  get '/delayed_job', to: DelayedJobWeb, anchor: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  include Concerns::DeviseRouting

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(
        :email,
        :name,
        :password,
        :password_confirmation
      )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navigation_for(user)
    if user.nil?
      render 'visitor_nav'
    elsif user.musician?
      render 'musician_nav'
    else
      render 'fan_nav'
    end
  end

  def campaign_controls_for(campaign, user)
    if campaign.successful?
      campaign_already_launched_button campaign
    elsif campaign_available_for_reservation? campaign, user
      reserve_campaign_button campaign
    else
      campaign_reserved_button campaign
    end
  end

  def reserve_campaign_button(campaign)
    link_to "Launch this sound <i class='icon-rocket'></i>".html_safe,
      campaign_reservations_path(campaign), method: :POST,
      class: 'btn btn-info btn-block'
  end

  def campaign_reserved_button(campaign)
    link_to "Reserved - Share to launch faster <i class='icon-time'></i>".html_safe,
      campaign_path(campaign),
      class: 'btn btn-info btn-block'
  end

  def campaign_already_launched_button(campaign)
    if current_user
       link_to "Launched, Download Now <i class='icon-download'></i>".html_safe, campaign.track_permalink,
      :target => "_blank",
      class: 'btn btn-info btn-block'
     else
      link_to "Sign in to Download <i class='icon-heart-empty'></i>".html_safe, new_user_session_path,
      class: "btn btn-info btn-block"
    end
  end

  private

  def campaign_available_for_reservation?(campaign, user)
    true if campaign.is_available_for?(user) &&
      campaign_is_not_owned_by?(campaign, user)
  end

  def campaign_is_not_owned_by?(campaign, user)
    true if campaign.musician.user != user
  end
end

app/views/application/_facebook_root.html.erb
<div id="fb-root"></div>

<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=482921591789638";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

app/views/application/_fan_nav.html.erb
<ul class="nav pull-right">
<li class="dropdown" >
<a href="#" class="dropdown-toggle" id="homelogo" data-toggle="dropdown">
  <i class="icon-user"></i> <%= current_user.name %>
  <b class="caret"></b>
</a>
<ul class="dropdown-menu">
  <li>
     <%= link_to uploads_path do %>
    <i class="fui-upload"></i> Uploads
  <% end %>
  </li>
  <li>
     <%= link_to user_tracks_path do %>
    <i class="fui-play"></i> My Sounds
  <% end %>
  </li>
  <li>
  <%= link_to user_settings_path do %>
    <i class="icon-cog"></i> Settings
  <% end %>
  </li>
  <li>
    <%= link_to sign_out_path do %>
      <i class="icon-download"></i> Logout
    <% end %>
  </li>
</ul>
</li>
</ul>

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>" class="alert alert-info">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end -%>
</div>

app/views/application/_footer.html.erb
<div class="bottom-menu bottom-menu-inverse ">
  <div class="container">
          <div class="row">
            <div class="span2 brand">
              <a href="#fakelink" class="fui-heart"></a>
            </div>

            <div class="span8">
              <ul class="bottom-links">
                <li><a href="#fakelink">Premium</a></li>

                <li><a href="#fakelink">About Us</a></li>
                <li><a href="#fakelink">Contact</a></li>
                <li class="active"><a href="#fakelink">Press</a></li>
                <li><a href="#fakelink">Privacy</a></li>
                <li><a href="#fakelink">Terms</a></li>
                <li><a href="#fakelink">Blog</a></li>
                <li><a href="#fakelink">FAQ</a></li>
                              </ul>
            </div>

            <div class="span2">
              <ul class="bottom-icons">
                <li><a href="#fakelink" class="fui-pinterest"></a></li>
                <li><a href="#fakelink" class="fui-facebook"></a></li>
                <li><a href="#fakelink" class="fui-twitter"></a></li>
              </ul>
            </div>
          </div>
      </div>
    </div>

app/views/application/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <%= link_to root_path, class: "brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
    <div class="nav-collapse collapse" id="nav-collapse-03">
    	 <ul class="nav pull-left">
  <li>
    <%= link_to music_path do %>
    <span class="fui-volume"></span> Music
    <% end %>
  </li>
 </ul>
     <%= navigation_for current_user %>
    </div>
  </div>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= javascript_include_tag "http://stratus.sc/stratus.js" %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_musician_nav.html.erb
 <ul class="nav pull-right">
<li>
<%= link_to dashboard_path do %>
  <i class="fui-windows"></i> Dashboard
<% end %>
</li>
<li class="dropdown" >
<a href="#" class="dropdown-toggle" id="homelogo" data-toggle="dropdown">
  <i class="fui-user"></i> <%= current_user.name %>
  <b class="caret"></b>
</a>
<ul class="dropdown-menu">
  <li>
     <%= link_to uploads_path do %>
    <i class="fui-upload"></i> Uploads
  <% end %>
  </li>
  <li>
     <%= link_to user_tracks_path do %>
    <i class="fui-play"></i> My Sounds
  <% end %>
  </li>
  <li>
  <%= link_to user_settings_path do %>
    <i class="icon-cog"></i> Settings
  <% end %>
  </li>
  <li>
  <%= link_to sign_out_path do %>
    <i class="icon-download"></i> Logout
  <% end %>
  </li>
</ul>
</li>
</ul>

app/views/application/_nav.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" id="homelogo" data-toggle="dropdown">
    <i class="icon-rocket"></i> Launchbase <span class="badge badge-info">0</span>
    <b class="caret"></b>
  </a>
<ul class="dropdown-menu">
  <li><a href="#">No new tracks ready for download</a></li>

  <li class="text-align-center"><%= link_to "View <i class='icon-rocket'></i> Launchbase".html_safe, launchbase_path %></li>
</ul>
</li>
<li class="dropdown introhome" >
<a href="#" class="dropdown-toggle" id="homelogo" data-toggle="dropdown">
  <i class="icon-user"></i> <%= current_user.name %>
  <b class="caret"></b>
</a>
<ul class="dropdown-menu">
  <li>
  <%= link_to user_settings_path do %>
    <i class="icon-cog"></i> Settings

  <% end %></li>
  <li>
  <%= link_to artist_lounge_path do %>
    <i class="icon-play"></i> Artist Lounge
  <% end %>
  </li>
  <li><%= link_to '#' do %><i class="icon-smile"></i> Help<% end %></li>
  <li>
    <%= link_to sign_out_path do %>
      <i class="icon-download"></i> Logout
    <% end %>
  </li>
</ul>
</li>

app/views/application/_player.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $.stratus({
      links: 'https://soundcloud.com/cr2records/the-disco-fries-open-your-eyes-psychic-type-remix',
      buying: false,
      download: false,
      stats: false,
    });
  });
</script>

app/views/application/_signupmodal.html.erb
 <div id="hello" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
        <div class="modal-header">
          <h3>Sign Up</h3>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="span3">
          
     <%= simple_form_for("user", :url => user_registration_path) do |f|  %>
          <%= f.input :name, placeholder: "Name", label: false, :required => true %></br>
          <%= f.input :email, placeholder: "email", label: false, :required => true  %></br>
          <%= f.input :password, placeholder: "password", label: false, :required => true  %></br>
           <%= f.input :password_confirmation, placeholder: "password confirmation", :required => true, label: false %>
        </div>


          <div class="span3">
            <a href="#fakelink" class="btn btn-small btn-social-facebook">
            <i class="fui-facebook"></i>
            Connect with Facebook
          </a>
          <p></p>
          <a href="#fakelink" class="btn btn-small btn-social-twitter">
            <i class="fui-twitter"></i>
            Connect with Twitter
          </a>
          </div>
          </div>
        </div>
        <div class="modal-footer">

          <%= f.submit "Signup",  class: "btn btn-primary btn-wide" %><% end %>



        </div>
      </div>

app/views/application/_visitor_nav.html.erb
 <ul class="nav pull-right">
                    <li class="divider"></li>
                    <li>
                      <a href="#hello" data-toggle="modal"><i class="fui-heart"></i> signup</a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fui-user"></i> login
                      </a>
                      <ul class="dropdown-menu">
                      <div class="formhome">
                        <%= simple_form_for("user", :url => user_session_path) do |f|  %>
                        <%= f.input :email, placeholder: "email", required: true, label: false %></br>
                         <%= f.input :password, placeholder: "password", required: true, label: false %></br>
                        <%= f.submit "login", class: "btn btn-info btn-block" %>
                        <% end %>
                      </div>
                      </ul>
                    </li>
              </ul>

         